# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sensor_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sensor_data.proto\x12\x07sensors\"q\n\x11SensorDataRequest\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\r\n\x05sound\x18\x02 \x01(\x02\x12\r\n\x05light\x18\x03 \x01(\x02\x12\x0c\n\x04\x64ust\x18\x04 \x01(\x02\x12\x0e\n\x06motion\x18\x05 \x01(\x05\x12\x0b\n\x03\x66\x61n\x18\x06 \x01(\x05\"6\n\x12SensorDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2^\n\x11SensorDataService\x12I\n\x0eSendSensorData\x12\x1a.sensors.SensorDataRequest\x1a\x1b.sensors.SensorDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORDATAREQUEST']._serialized_start=30
  _globals['_SENSORDATAREQUEST']._serialized_end=143
  _globals['_SENSORDATARESPONSE']._serialized_start=145
  _globals['_SENSORDATARESPONSE']._serialized_end=199
  _globals['_SENSORDATASERVICE']._serialized_start=201
  _globals['_SENSORDATASERVICE']._serialized_end=295
# @@protoc_insertion_point(module_scope)
