# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sensor_data_pb2 as sensor__data__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sensor_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SensorDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendSensorData = channel.unary_unary(
                '/sensors.SensorDataService/SendSensorData',
                request_serializer=sensor__data__pb2.SensorDataRequest.SerializeToString,
                response_deserializer=sensor__data__pb2.SensorDataResponse.FromString,
                _registered_method=True)


class SensorDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendSensorData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendSensorData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSensorData,
                    request_deserializer=sensor__data__pb2.SensorDataRequest.FromString,
                    response_serializer=sensor__data__pb2.SensorDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sensors.SensorDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sensors.SensorDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SensorDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendSensorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sensors.SensorDataService/SendSensorData',
            sensor__data__pb2.SensorDataRequest.SerializeToString,
            sensor__data__pb2.SensorDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
